### ISSUE TITLE
Missing import in Gulpfile

### ISSUE THREAD

**Issue by jrasanen** [ronilaukkarinen/modern-html5-boilerplate#1]
Error is thrown when I run gulp

```
ReferenceError: runSequence is not defined
```

**Comment by rollecode** [comment]
Forgot to define version requirements for this project, new repo - pardon me.

What does `npm --version` and `gulp --version` output for you?

**Comment by jrasanen** [comment]
I use nvm to manage node versions

```
npm --version
1.4.28
```

Gulp was installed via the supplied package.json

```
gulp --version
[16:52:04] CLI version 3.8.10
```

**Comment by rollecode** [comment]
Note: I have the same versions and I have no idea why I didn't get that ReferenceError.

**Comment by jrasanen** [comment]
Gulpfile just doesn't import runSequence anywhere: https://www.npmjs.com/package/run-sequence

**Comment by rollecode** [comment]
It should now. I fixed this in just now, committed too early, sorry about that.
