### ISSUE TITLE
Exclude compiled files from git, maybe move them to build/ directory

### ISSUE THREAD

**Issue by jrasanen** [ronilaukkarinen/modern-html5-boilerplate#3]
Directory separation for compiled files and assets would be nice because
- Deploying only the "build" directory is easier
- Keeping the git-repository cleaner is easier
- Asset revisioning is easier

**Comment by rollecode** [comment]
FYI, I use Capistrano for deployment and used to symlink only the files/folders I need. No need for asset revisioning here in my opinion. This being a little too app-like-approach for me, but let's stick with it here. Thanks for the contribution!
